import type PocketBase from 'pocketbase';

// This file would normally be generated by a PocketBase typegen tool
// For now, we'll use the base PocketBase type
export type TypedPocketBase = PocketBase;